a=int(input("Enter first number: "))
b=int(input("Enter second number: "))
print("Addition: "+str(a+b))
print("Subtraction: "+str(a-b))
print("Multiplication: "+str(a*b))
print("Division: "+str(a/b))
print("Modulus(remainder): "+str(a%b))
print("Exponentiation: "+str(a**b))
print("Floor Division: "+str(a//b))
getch()